<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\User;

/**
 * SocialAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialAccountRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByUserWithEvents(User $user)
    {
        return $this->createQueryBuilder('a')
                    ->select('a, e')
                    ->leftJoin('a.events', 'e')
                    ->where('a.user = :user')
                    ->setParameter('user', $user)
                    ->getQuery()
                    ->getResult();
    }

    public function findForUpdateEvents($limit = 30, $updateMinutesCount = 5)
    {
        $updateTime = (new \DateTime())->modify('-' . $updateMinutesCount . ' minutes');
        $query      = $this->createQueryBuilder('a');
        $result     = $query
            ->where(
                $query->expr()->orX(
                    'a.eventsUpdatedAt < :updateTime',
                    $query->expr()->isNull('a.eventsUpdatedAt')
                )
            )
            ->setParameters([
                'updateTime' => $updateTime->format('Y-m-d H:i:s'),
            ])
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();

        return $result;

    }
}
